const fons = [
    require("./fon/smallFon0.png"),
    require("./fon/smallFon1.png"),
    require("./fon/smallFon2.png"),
    require("./fon/smallFon3.png"),
    require("./fon/smallFon4.png"),
    require("./fon/smallFon5.png"),
    require("./fon/smallFon6.png"),
    require("./fon/smallFon7.png"),
    require("./fon/smallFon8.png"),
    require("./fon/smallFon9.png"),
    require("./fon/smallFon10.png"),
    require("./fon/smallFon11.png"),
    require("./fon/smallFon12.png"),
    require("./fon/smallFon13.png"),
    require("./fon/smallFon14.png"),
    require("./fon/smallFon15.png"),
    require("./fon/smallFon16.png"),
    require("./fon/smallFon17.png"),
    require("./fon/smallFon18.png"),
    require("./fon/smallFon19.png"),
    require("./fon/smallFon20.png"),
    require("./fon/smallFon21.png"),
    require("./fon/smallFon22.png"),
    require("./fon/smallFon23.png"),
    require("./fon/smallFon24.png"),
    require("./fon/smallFon25.png"),
    require("./fon/smallFon26.png"),
    require("./fon/smallFon27.png"),
    require("./fon/smallFon28.png"),
    require("./fon/smallFon29.png"),
];

export default fons;